### PR TITLE
Untested Changes to Add Chrome Profile Targetting

### PR DESCRIPTION
**Pull request by reb00tz**
My _totally_ untested, "quick and dirty" changes to allow for Chrome profile targeting.

Apologies in advance: Unable to test due to lack of Go compiler and knowledge of Go (and lack of Mac OSX also)...

Note that according to https://superuser.com/questions/759535/open-google-chrome-specific-profile-from-command-line-macm, OSX may require "-n" parameter for Chrome to open with specific profile (if another instance of Chrome is already running).

### CODE REVIEW

**Comment by g3rv4** [comment]
thanks for this! are you using Windows? I don't think I'm renewing my code signing cert, so I'll test this and merge before it expires.

**Comment by reb00tz** [comment]
Hi,

Yes, I’m on Windows – no access to Mac. If you can point me to “quick start” Go compilation + Firefox addon testing instructions, I’ll try to compile and test it also…

Thanks,

**Comment by g3rv4** [comment]
I took your changes and did a few more to make it work :) you can see all of it on 97b71c6259dc433b1e2d6b986463ee32e7c7cb36

I was able to build & test it both on OSX and Windows. I will do my best to ship it to the store tomorrow.

**Comment by g3rv4** [comment]
done! you can download the latest native application from https://onchro.me/native-applications and you should also update your browser extension to the v0.3

**Pull request closed without merging**
