### PR TITLE
Allow exclusion matches

### PR DESCRIPTION
**Pull request by px0**
We have a few subdomains that I'd like to keep accessing through firefox; all the other ones should be opened in Chrome.

This PR adds the ability to add matches to an 'exclusions' list that is, at its easiest, just a list of words that 'blacklist' a URL from being opened in Chrome, or a more advanced regular expression for more finegrained control.

image

Thank you for this plugin, it's making my (and my colleagues') life much easier!

### CODE REVIEW

**Comment by g3rv4** [comment]
looks neat! at some point I'll have to spend some time improving its UI now that I'm seeing some people using it.

I'll review it this week.

**Comment by px0** [comment]
> looks neat! at some point I'll have to spend some time improving its UI now that I'm seeing some people using it.

Eeeeh, I like the simplicity of it. Plus, if I'd had to mess around with CSS, I might have never made this PR ;)

> I'll review it this week.

👍

**Comment by g3rv4** [comment]
Alright! I made a couple changes here: e552623416c8e85b03c3ab69767cde98a2155fc9

can you either cherry pick it or [give me permissions to collaborate on this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

thanks!

**Comment by g3rv4** [comment]
my bad, you had already done so. I've just merged it and submitted v0.3.1 to the Firefox store. It should be available for you to upgrade.

Thanks again!

**Comment by px0** [comment]
Awesome, thanks :D

**Pull request merged**
